apiVersion: v1
kind: Pod
metadata:
  name: direct-thpt-receiver
  namespace: perf-eventing
  labels:
    role: direct-thpt-consumer
spec:
  restartPolicy: Never
  containers:
    - name: "direct-thpt-receiver"
      image: github.com/slinkydeveloper/eventing-thpt/cmd/receiver
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        requests:
          cpu: 1
          memory: 4Gi
      ports:
        - containerPort: 8080
        - containerPort: 2112
          name: metrics
      args:
        - "--max-throughput-expected=2100"
        - "--verbose"
